name: Automatic version bumping
on:
  schedule:
    - cron: '3 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "BIG UGLY FROGMINER"
          git config user.email BIG_UGLY_FROGMINER@froggi.es
          ./update-kernel-versions.sh
          changes=$(cat kernel_updates)
          if [ -n "$changes" ]; then
            git add PKGBUILD linux-tkg-config/prepare
            git commit --author="Adel KARA SLIMANE <adel.ks@zegrapher.com>" -m "version bumps:$changes"
            git push
          fi
