name: config changes checker
on:
  schedule:
    - cron: '47 0 * * 6' # "At 12:47 AM, only on Saturday"
  workflow_dispatch:

env:
  _distro: Ubuntu
  _logging_use_script: "no"
  _git_mirror: "gregkh"

jobs:

  check-patches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout linux-tkg
        uses: actions/checkout@v4

      - name: Install dependencies
        id: unclean-print
        run: ./install.sh install-deps

      - name: List failed config changes for all kernel versions
        run: ./linux-tkg-config/config-checker > $GITHUB_STEP_SUMMARY
